// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-acKdK8eK5zwj9802jpxfVjkZ438JOXg',
    appId: '1:864839720244:web:3be51bc5d643ca63299961',
    messagingSenderId: '864839720244',
    projectId: 'alu-launchpad-89ef9',
    authDomain: 'alu-launchpad-89ef9.firebaseapp.com',
    storageBucket: 'alu-launchpad-89ef9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFsRBFDP57N8MGba07_S0Aymb5or30RCM',
    appId: '1:864839720244:android:ef4e81fa9e9ea8c8299961',
    messagingSenderId: '864839720244',
    projectId: 'alu-launchpad-89ef9',
    storageBucket: 'alu-launchpad-89ef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzhtDlqYVpJ9M2-Y0JoOs_2-eMEDA5n2o',
    appId: '1:864839720244:ios:af314a6671da0292299961',
    messagingSenderId: '864839720244',
    projectId: 'alu-launchpad-89ef9',
    storageBucket: 'alu-launchpad-89ef9.firebasestorage.app',
    iosBundleId: 'com.example.aluLaunchpad',
  );
}
